// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXQUGmOUk7SOpjGyd02IheT3r8yR1dNIU',
    appId: '1:994417666781:web:818f18f472d2feeee3c934',
    messagingSenderId: '994417666781',
    projectId: 'humorfy-76a25',
    authDomain: 'humorfy-76a25.firebaseapp.com',
    storageBucket: 'humorfy-76a25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEZmnD9E9fA7ZRFI-w28L6PZQ8KxIYT5Q',
    appId: '1:994417666781:android:8b4640a6d11e9daae3c934',
    messagingSenderId: '994417666781',
    projectId: 'humorfy-76a25',
    storageBucket: 'humorfy-76a25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5p3qUxPsqBhexnn-TP9dKDVXR9uVF0ss',
    appId: '1:994417666781:ios:0291ac0a9e0e9a55e3c934',
    messagingSenderId: '994417666781',
    projectId: 'humorfy-76a25',
    storageBucket: 'humorfy-76a25.appspot.com',
    iosBundleId: 'com.example.humorfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5p3qUxPsqBhexnn-TP9dKDVXR9uVF0ss',
    appId: '1:994417666781:ios:06f5c51f07c00065e3c934',
    messagingSenderId: '994417666781',
    projectId: 'humorfy-76a25',
    storageBucket: 'humorfy-76a25.appspot.com',
    iosBundleId: 'com.example.humorfy.RunnerTests',
  );
}
